version: "2"

services:
  web:
    container_name: web
    image: pewdie/php:7.3-apache
    build: .
    networks:
      - app-tier
    ports:
      - 8082:80
    volumes:
      - ./:/var/www/html/
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:5.6
    command:
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - app-tier
    ports:
      - 3306:3306

  adminer:
    image: adminer:4.7.5
    restart: always
    networks:
      - app-tier
    ports:
      - 8081:8080



networks:
  app-tier:
    driver: bridge